
import random

tag1 = ["#nycart", "#contemporaryart", "#contemporaryartist", "#digitalart", "#artedigital","#nftart", "#nftartist", "#nftartists", "#nftartgallery", "#nftartwork", "#nftcollector", "#nftcommunity", "#nfts", "#cryptoart", "#opensea", "#nftcollectors", "#ethereum", "#nftcollectibles", "#nftdrop", "#blockchain", "#cryptoartist", "#nftcollection", "#openseanft", "#eth", "#metaverse", "#newstart", "#newart", "#newartist", "#artnews", "#newartwork", "#newyorker", "#newyork_instagram", "#newyorknewyork", "#chicagoartist", "#chicagogram", "#artmuseum", "#artbasel", "#contemporaryart", "#contemporaryartist", "#contemporaryartwork", "#artgallery", "#galleryart", "#nftartgallery", "#earthgallery", "#beauty", "#photography", "#happy", "#bestoftheday", "#motivation", "#fun", "#instalike", "#amazing", "#fashion", "#love", "#instagram", "#beautiful", "#style", "#life", "#design", "#japaneseart"]

tag1_list = random.sample(tag1, 4)

tag2 = ["#nycartist","#nycartists" ,"#artcontemporary" ,"#contemporaryfineart","#digitalfanart" ,"#nftarts" ,"#nftartcollector" ,"#nftartcollector" ,"#openseanftart" ,"#raredigitalart" ,"#nftnews" ,"#nftgallery" ,"#nftmarketplace" ,"#nftmagazine" ,"#nfthesearch" ,"#rarible" ,"#nftgiveaway" ,"#cryptopunks" ,"#openseaart" ,"#cryptomonnaie" ,"#cryptoartwork" ,"#nftindonesia" ,"#元宇宙" ,"#cryptopunk" ,"#newyorkart" ,"#newmediaart" ,"#newcontemporaryart" ,"#newbornart" ,"#newyearnewstart" ,"#newweeknewstart" ,"#newdaynewstart" ,"#neworleansart" ,"#newyorkartist" ,"#newearth" ,"#newyearparty" ,"#newyearsparty" ,"#newartists" ,"#newapartment" ,"#chicagoart" ,"#chicagostreetart" ,"#chicagomakeupartist" ,"#chicagotattooartist" ,"#chicagoartists" ,"#artcontemporary" ,"#contemporaryfineart" ,"#contemporaryfigurativeart" ,"#contemporaryafricanart" ,"#contemporaryartcurator" ,"#contemporaryartists" ,"#contemporaryartgallery" ,"#contemporaryartcollectors" ,"#contemporaryartcollector" ,"#contemporaryarts" ,"#newcontemporaryart" ,"#contemporaryartmuseum" ,"#urbancontemporaryart" ,"#museumofcontemporaryart" ,"#artsgallery" ,"#galleryartist" ,"#contemporaryartgallery" ,"#onlineartgallery" ,"#artgallerys" ,"#fluidartgallery" ,"#artgalleryfabrics" ,"#fineartgallery" ,"#artgallerynyc" ,"#animeartgallery" ,"#nailartgallery" ,"#streetartgallery" ,"#paintingartgallery" ,"#modernartgallery" ,"#newyorkartgallery" ,"#moderngallery" ,"#modernartgallery" ,"#japanesenailart" ,"#japanesetattooart" ,"#japaneseartist"]

tag2_list = random.sample(tag2, 11)

tag3 = ["#nycartscene" ,"#contemporaryphotoart" ,"#contemporaryabstractart" ,"#digitalabstractart" ,"#digitalillustrationsart" ,"#nftartistsoninstagram" ,"#nftartworks","#nftartistsoninstagram" ,"#nftartworks" ,"#nftartworld" ,"#nftartfinance" ,"#nftartoftheday" ,"#nftartis" ,"#nftartcollection" ,"#openseanftartist" ,"#nftartdaily" ,"#nftartsale" ,"#nftartistsofinstagram" ,"#nftartdrop" ,"#nftartmedia" ,"#nftarti̇st" ,"#nftartgang" ,"#kadoilustrasi" ,"#nonfungible" ,"#mintable" ,"#nftathome" ,"#avax" ,"#基金" ,"#理財規劃" ,"#網格交易" ,"#punctualism_art" ,"#bitcoinbr" ,"#metaversegeneration" ,"#annahilta" ,"#metaverseinfluencer" ,"#rainbowland" ,"#abstractartgallery" ,"#newyorkstreetart" ,"#newmexicoart" ,"#newspaperart" ,"#newyorkcityart" ,"#newheart" ,"#newschoolart" ,"#newenglandart" ,"#newageart" ,"#newcastleart" ,"#artnew" ,"#newnailart" ,"#newjerseyart" ,"#newyearart" ,"#newfoundlandart" ,"#newyorkacademyofart" ,"#artchicago" ,"#chicagonailart" ,"#artinstitutechicago" ,"#artofchicago" ,"#artinchicago" ,"#artensembleofchicago" ,"#chicagoinstituteofart" ,"#chicagopublicart" ,"#chicagotattooart" ,"#artravechicago" ,"#artgallerychicago" ,"#chicagograffitiart" ,"#artbeatchicago" ,"#artdesignchicago" ,"#artandsciencesalonchicago" ,"#contemporaryphotoart" ,"#contemporaryabstractart" ,"#contemporarytextileart" ,"#contemporaryfiberart" ,"#contemporaryphotographyart" ,"#contemporaryaustralianart" ,"#contemporarywesternart" ,"#contemporaryindianart" ,"#contemporarycollageart" ,"#contemporaryglassart" ,"#contemporarycanadianart" ,"#contemporarycubanart" ,"#contemporarychineseart" ,"#contemporaryembroideryart" ,"#contemporaryblackart" ,"#artistgallery" ,"#galleryofart" ,"#artdigitalgallery" ,"#artpeoplegallery" ,"#galleryofmodernart" ,"#gallerywallart" ,"#artphotographygallery" ,"#artistrungallery" ,"#artofgallery" ,"#arteyegallery" ,"#artegallery" ,"#artspacegallery" ,"#artmajeurgallery" ,"#artlifegallery" ,"#artforsalebygallery" ,"#modernedengallery" ,"#modernrocksgallery" ,"#moderntimesgallery" ,"#modernartistgallery" ,"#modernartistsgallery" ,"#modernshapesgallery" ,"#modernismgallery" ,"#modernartworkgallery" ,"#moderndesigngallery" ,"#modernistcuisinegallery" ,"#moderntategallery" ,"#modernandcontemporaryartgallery" ,"#galleryofmodernart" ,"#tatemoderngallery" ,"#scottishnationalgalleryofmodernart" ,"#japanesecontemporaryart" ,"#japanesefanart" ,"#artjapanese" ,"#japanesepopart" ,"#japaneseflowerart" ,"#japanesefineart" ,"#japanesemartialart" ,"#japaneseinspiredart"]

tag3_list = random.sample(tag3, 15)

all_tags = tag1_list + tag2_list + tag3_list

print(*all_tags)

